### ISSUE TITLE
Update the css for twemoji 2.0?

### ISSUE THREAD

**Issue by robwco** [ellekasai/twemoji-awesome#11]
I was wondering if you're going to be updating the CSS file for the new twemoji 2.0 icons?

twemoji.maxcdn.com/2/twemoji.min.js

**Comment by Rokt33r** [comment]
I also have same problem. So, I deal with it on my own.
Check this repo. https://github.com/Rokt33r/emoji-magic-box
CDN: https://cdn.rawgit.com/Rokt33r/emoji-magic-box/v1.0.1/dist/twa.css

**Comment by JuanitoFatas** [comment]
@robwco Here is a twemoji 2.0 yaml file you can use: https://github.com/jollygoodcode/emoji-keywords/blob/master/twemoji/v2/keywords.yaml.

**Comment by ellekasai** [comment]
Hey guys! So sorry for my late reply. I just merged this pull request, so should be ok now :)!! Thank you for opening this issue!

https://github.com/ellekasai/twemoji-awesome/pull/14
