### ISSUE TITLE
Where is the detective?

### ISSUE THREAD

**Issue by ghost** [ellekasai/twemoji-awesome#13]
Hey,

I can't find the detective or spion? Is it included?

https://abs.twimg.com/emoji/v2/72x72/1f575.png

Best,
Christian

**Comment by ellekasai** [comment]
So sorry for my late reply. I just merged this pull request, so should be ok now :)!! Thank you for opening this issue!

https://github.com/ellekasai/twemoji-awesome/pull/14

**Comment by ghost** [comment]
Thank you so much. The detective is my favorite emoji. :heart_eyes:
