### ISSUE TITLE
Incorrect links?

### ISSUE THREAD

**Issue by joshuabaker** [ellekasai/twemoji-awesome#5]
:disappointed_relieved: (`:disappointed_relieved:`) and :relieved: (`:relieved:`) appear to be broken.

http://jsbin.com/purayepafu/

**Comment by ellekasai** [comment]
So sorry for my late reply. I just merged this pull request, so should be ok now :)!! Thank you for opening this issue!

https://github.com/ellekasai/twemoji-awesome/pull/14
